# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build - runified

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
          version: 8


      - name: Patch Version ${{ env.GITHUB_REF }}
        run: |
          cd ts ; node ../.github/workflows/patch-package.json.js "origin/head/0.0.0-smoke"
          git diff

      - name: Patch Version ${{ env.GITHUB_REF }}
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd ts ; node ../.github/workflows/patch-package.json.js "$GITHUB_REF"
          git diff

      - name: Build JS runified
        run: |
          cd ts
          pnpm install
          pnpm run generate
          pnpm run prettier --check
          pnpm run lint
          pnpm run build
          pnpm run test
          pnpm run smoke

      - uses: mabels/neckless@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          version: v0.1.16

      - name: Publish runified NPM
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NECKLESS_PRIVKEY: ${{ secrets.NECKLESS_PRIVKEY }}
        run: |
          eval $(neckless kv ls --shKeyValue --ghAddMask NPM_PASS  NPM_USER "NPM_TOTP@Totp()")
          # env | sort | grep NPM
          token=$(curl -H "npm-otp: $NPM_TOTP" \
               -X PUT \
               -H 'content-type: application/json' \
               -d "{\"name\":\"$NPM_USER\", \"password\": \"$NPM_PASS\"}" \
               https://registry.npmjs.org/-/user/org.couchdb.user:$NPM_USER | jq -r .token)
          echo "//registry.npmjs.org/:_authToken=$token" > $HOME/.npmrc
          cd ts
          cd pubdir
          pnpm publish --otp=$(neckless kv ls --onlyValue "NPM_TOTP@Totp()") --access public
